name: llg CI
on:
  workflow_call:

jobs:
  App-build-workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Dependencies
      working-directory: ./.
      run: npm ci
    - name: Build llg
      working-directory: ./.
      run: npm run build
    - name: Upload llg artifact
      uses: actions/upload-artifact@v4
      with:
        name: llg
        path: ./dist